apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "shipwright-build.fullname" . }}-controller
  labels:
  {{- include "shipwright-build.labels" . | nindent 4 }}
rules:
  - apiGroups: ['']
    resources: ['configmaps']
    verbs: ['get', 'create', 'update']
  - apiGroups: ['coordination.k8s.io']
    resources: ['leases']
    verbs: ['create', 'get', 'update']
  - apiGroups: ['']
    resources: ['events']
    verbs: ['create']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "shipwright-build.fullname" . }}-controller
  labels:
  {{- include "shipwright-build.labels" . | nindent 4 }}
rules:
  - apiGroups: ['shipwright.io']
    resources: ['buildruns']
    # The build-run-deletion annotation sets an owner ref on BuildRun objects.
    # With the OwnerReferencesPermissionEnforcement admission controller enabled, controllers need the "delete" permission on objects that they set owner references on.
    verbs: ['get', 'list', 'watch', 'update', 'delete']
  - apiGroups: ['shipwright.io']
    # BuildRuns are set as the owners of Tekton TaskRuns.
    # With the OwnerReferencesPermissionEnforcement admission controller enabled, controllers need the "update" permission on the finalizer of the parent object in the owner reference.
    resources: ['buildruns/finalizers']
    verbs: ['update']
  - apiGroups: ['shipwright.io']
    resources: ['buildruns/status']
    verbs: ['update']
  - apiGroups: ['shipwright.io']
    resources: ['builds']
    verbs: ['get', 'list', 'watch']
  - apiGroups: ['shipwright.io']
    # The build-run-deletion annotation makes Builds an owner of BuildRun objects.
    # With the OwnerReferencesPermissionEnforcement admission controller enabled, controllers need the "update" permission on the finalizer of the parent object in the owner reference.
    resources: ['builds/finalizers']
    verbs: ['update']
  - apiGroups: ['shipwright.io']
    resources: ['builds/status']
    verbs: ['update']
  - apiGroups: ['shipwright.io']
    resources: ['buildstrategies']
    verbs: ['get', 'list', 'watch']
  - apiGroups: ['shipwright.io']
    resources: ['clusterbuildstrategies']
    verbs: ['get', 'list', 'watch']
  - apiGroups: ['tekton.dev']
    resources: ['taskruns']
    # BuildRuns are set as the owners of Tekton TaskRuns.
    # With the OwnerReferencesPermissionEnforcement admission controller enabled, controllers need the "delete" permission on objects that they set owner references on.
    verbs: ['get', 'list', 'watch', 'create', 'delete', 'patch']
  - apiGroups: ['']
    resources: ['pods']
    verbs: ['get', 'list', 'watch']
  - apiGroups: ['']
    resources: ['secrets']
    verbs: ['get', 'list', 'watch']
  - apiGroups: ['']
    resources: ['configmaps']
    verbs: ['list']
  - apiGroups: ['']
    resources: ['serviceaccounts']
    verbs: ['get', 'list', 'watch', 'create', 'update', 'delete']

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "shipwright-build.fullname" . }}-webhook
  labels:
  {{- include "shipwright-build.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - events
      - configmaps
      - secrets
      - limitranges
      - namespaces
      - services
    verbs:
      - '*'
  - apiGroups:
      - admissionregistration.k8s.io
      - admissionregistration.k8s.io/v1beta1
    resources:
      - validatingwebhookconfigurations
    verbs:
      - '*'

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "shipwright-build.fullname" . }}-controller
  labels:
  {{- include "shipwright-build.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "shipwright-build.fullname" . }}-controller
    namespace: shipwright-build
roleRef:
  kind: ClusterRole
  name: {{ include "shipwright-build.fullname" . }}-controller
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "shipwright-build.fullname" . }}-controller
  labels:
  {{- include "shipwright-build.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "shipwright-build.fullname" . }}-controller
    namespace: shipwright-build
roleRef:
  kind: Role
  name: {{ include "shipwright-build.fullname" . }}-controller
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "shipwright-build.fullname" . }}-webhook
  labels:
  {{- include "shipwright-build.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "shipwright-build.fullname" . }}-webhook
subjects:
  - kind: ServiceAccount
    name: {{ include "shipwright-build.fullname" . }}-webhook
    namespace: shipwright-build

---
# aggregate RBAC
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  {{- include "shipwright-build.labels" . | nindent 4 }}
  name: {{ include "shipwright-build.fullname" . }}-aggregate-view
rules:
  - apiGroups: ['shipwright.io']
    resources: ['clusterbuildstrategies']
    verbs: ['get', 'list', 'watch']
  - apiGroups: ['shipwright.io']
    resources: ['buildstrategies']
    verbs: ['get', 'list', 'watch']
  - apiGroups: ['shipwright.io']
    resources: ['builds']
    verbs: ['get', 'list', 'watch']
  - apiGroups: ['shipwright.io']
    resources: ['buildruns']
    verbs: ['get', 'list', 'watch']

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
  {{- include "shipwright-build.labels" . | nindent 4 }}
  name: {{ include "shipwright-build.fullname" . }}-aggregate-edit
rules:
  - apiGroups: ['shipwright.io']
    resources: ['clusterbuildstrategies']
    verbs: ['get', 'list', 'watch']
  - apiGroups: ['shipwright.io']
    resources: ['buildstrategies']
    verbs: ['get', 'list', 'watch', 'create', 'update', 'patch', 'delete']
  - apiGroups: ['shipwright.io']
    resources: ['builds']
    verbs: ['get', 'list', 'watch', 'create', 'update', 'patch', 'delete']
  - apiGroups: ['shipwright.io']
    resources: ['buildruns']
    verbs: ['get', 'list', 'watch', 'create', 'update', 'patch', 'delete']
