apiVersion: v1
kind: Service
metadata:
  name: shp-build-webhook
  labels:
  {{- include "shipwright-build.labels" . | nindent 4 }}
spec:
  ports:
    - name: https-webhook
      port: 443
      targetPort: 8443
  selector:
    name: shp-build-webhook